### ISSUE TITLE
VsCoq does not ignore comments in _CoqProject

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/vscoq#292]
I have a `_CoqProjectFile` in my project root which starts with:
```
-Q ./CoqBuild CoqBuild
-Q ./CoqLocal CoqLocal
# -Q /Users/msoegtrop/CoqVST/VST-work-3 VST
```
The state in this commented out VST working folder has been compiled with 8.13, but I am working with 8.15.
When I go over `Require Import VST.floyd.proofauto.` in a file I get the error:
```
File /Users/msoegtrop/CoqVST/VST-work-3/floyd/proofauto.vo has bad version number 81300 (expected 81500)
```
which is wrong, because the -Q directive in _CoqProject is commented out. When I delete this comment line, things work as expected. Other tools like CoqIDE honor the comment sign in _CoqProject files.

**Comment by Blaisorblade** [comment]
Ah, this is a bug in either `node_modules/string-argv/index.js` or the code below in `server/src/CoqProject.ts` — neither strips comment lines at all, they just skip words.
```
  private static parseCoqProject(text: string) : string[] {
    const args : string[] = [];
    const projectArgs : string[] = stringArgv(text);
    for(let idx = 0; idx < projectArgs.length; ++idx) {
      const opt = projectArgs[idx]
      if(opt === '-R')
        args.push('-R', projectArgs[++idx], projectArgs[++idx])
      else if(opt === '-I')
        args.push('-I', projectArgs[++idx])
      else if(opt === '-Q')
        args.push('-Q', projectArgs[++idx], projectArgs[++idx])
      else if(opt === '-arg')
        args.push(...stringArgv(projectArgs[++idx]))
    }
    return args;
  }
```

**Comment by Blaisorblade** [comment]
I've now noticed that Proof General does not implement the desired behavior either, but hopefully we can still refuse compatibility with PG...

If I add `# -arg -noinit` in `_CoqProject`, both VsCoq and Proof General pass `-noinit` to `coqtop`/`coqidetop.opt`...

**Comment by rtetley** [comment]
This is fixed in VsCoq2 (realised when testing #897)
